name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_THM }}

      # ⭐ Étape ajoutée : supprimer l’image existante pour forcer un changement
      - name: Remove old badge
        run: |
          rm -f ./assets/thm_propic.png

      # Workflow TryHackMe original
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "julienlrzl"
          GITHUB_TOKEN: ${{ secrets.PAT_THM }}
